### ISSUE TITLE
Using invalid phone numbers in testing.

### ISSUE THREAD

**Issue by schneiderderek** [fcevado/phone#102]
I was wondering if you'd considered a feature that would "turn off" area code checking in certain environments via a configuration option. I typically use invalid phone numbers (ex. +1-555-555-5555) in testing intentionally to avoid the chance of accidentally sending out a real SMS or telephone call. Invalid phone numbers are also used by Twilio for testing (https://www.twilio.com/docs/api/rest/test-credentials). I think it would be valuable to have this feature for testing purposes.

Is this something you would consider adding to the library?

**Comment by fcevado** [comment]
@schneiderderek I think it's out of the scope, at least for this library. I understand your concerns but I would approach this in a different manner. I don't know what kind of application you're building but I strongly suggest this article by José Valim:
http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/

**Comment by schneiderderek** [comment]
@fcevado Thanks for the feedback
