### ISSUE TITLE
Hex release for v0.5.9

### ISSUE THREAD

**Issue by nyxcharon** [fcevado/phone#161]
Quick question - is there any hold ups for cutting a release for v0.5.9 to hex? 

I'd like to use the new version for the updated area codes and can certainly do so by switching to a git sha, but would much rather update the standard way.

**Comment by fcevado** [comment]
i thought i had published 0.5.9, sorry for that.
i just published 0.5.10 that also fixes an issue and some compilatin warnings on elixir 1.18
