### ISSUE TITLE
Brazilian mobile phone numbers cannot be parsed

### ISSUE THREAD

**Issue by fearenales** [fcevado/phone#64]
While trying to parse a brazilian mobile phone number (2-digit country code + 2-digit local area code + 9-digit phone number), I've got this error:

```elixir
Phone.parse("+5511912345678")
#=> {:error, "Not a valid phone number."}
```

**Comment by fcevado** [comment]
Brazilian phone numbers with nine digits, the first digit is always 9 and the second digit must be 9 or 8, since only cellphone numbers migrated from 8 to 9 digits. The old 8 digits cellphone numbers always started with 8 or 9. This is accordingly with the `Anatel` specification.

**Comment by fearenales** [comment]
I'm sorry, I've just tried to obfuscate my own number, but I've tested with a valid number as well (which respects the rules you stated above), and the same error occurs.

**Comment by fearenales** [comment]
Ops, I've just noticed my own number does not follow the rules you've stated:
`+551194*******`, i.e., after the first digit `9`, there's no `9` nor `8`, but `4`.

**Comment by fcevado** [comment]
I'm reopening the issue... I gonna review the brazilian numbering plan and see what official info I can find.

**Comment by fcevado** [comment]
Sorry, my mistake... I was reading the [brazilian numbering plan](http://www.anatel.gov.br/setorregulado/index.php/plano-de-numeracao-brasileiro) and found out that for area codes 11 to 19 any nine digit number starting with 9 is valid.

**Comment by fcevado** [comment]
I'm preparing the release with this correction. Thank you @fearenales, hope that this lib is being useful.
