### ISSUE TITLE
Issue parsing Irish phone numbers

### ISSUE THREAD

**Issue by aaronrenner** [fcevado/phone#88]
I am having an issue getting irish phone numbers to parse correctly. I'm not sure what part of the phone number is the "area code", but here are some sample phone numbers.

+353 1 276 1923 - McDonald's, Bray, County Wicklow, Ireland
+353 402 39874 - McDonald's, Arklow, County Wicklow, Ireland
+353 1 872 4487 - McDonald's, 62 O'Connell Street Upper Dublin Dublin 1 O'Connell Street Upper, North City, Dublin 1, Ireland

Also what do you think about creating a test file for each country with sample phone numbers in it? For example, Ireland's tests would be in `test/phone/ie_test.exs`.

**Comment by aaronrenner** [comment]
Here's a wikipedia article about Irish phone numbers: https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Republic_of_Ireland. It looks like they have some interesting area codes. It looks like Dublin's area code is 1, and Arklow's area code is 402. In this document local numbers appear to be dialed with 01 xxx xxxx and when using e164 format, the same number would be dialed 353 01 xxx xxxx.

**Comment by fcevado** [comment]
I'm updating the regex, I guess something like that will work for a while:
`^(353)(1|402|404|505|90|[2-9][1-9])(.{5,7})$`
I'll update the master, but I'll try to finish my changes to increase performance this weekend so I can put everything in one release.

**Comment by fcevado** [comment]
> Also what do you think about creating a test file for each country with sample phone numbers in it? For example, Ireland's tests would be in test/phone/ie_test.exs

I had thought that a while ago, I was planning to do that on this end of the year. Initially I would do that only for the countries with area code specifications(all from NANP and Brazil by now, I think I can do Ireland too, since it's a small one).

**Comment by aaronrenner** [comment]
Awesome! Thanks for your help with this. I'll go ahead and close the issue.
